In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import *

In [11]:
data = load_iris()
df = pd.DataFrame(data.data, columns=data.feature_names)
y = pd.Series(data.target)
df


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [12]:
from sklearn.preprocessing import StandardScaler
df_scaled = StandardScaler().fit_transform(df)


In [13]:
features = df_scaled.T
cov_matrix = np.cov(features,bias=True)
cov_matrix

array([[ 1.        , -0.11756978,  0.87175378,  0.81794113],
       [-0.11756978,  1.        , -0.4284401 , -0.36612593],
       [ 0.87175378, -0.4284401 ,  1.        ,  0.96286543],
       [ 0.81794113, -0.36612593,  0.96286543,  1.        ]])

In [15]:
values, vectors = np.linalg.eig(cov_matrix)
print(values)
print(vectors)

[2.91849782 0.91403047 0.14675688 0.02071484]
[[ 0.52106591 -0.37741762 -0.71956635  0.26128628]
 [-0.26934744 -0.92329566  0.24438178 -0.12350962]
 [ 0.5804131  -0.02449161  0.14212637 -0.80144925]
 [ 0.56485654 -0.06694199  0.63427274  0.52359713]]


In [16]:
explained_virances = []
for i in range (len(values)):
    explained_virances.append(values[i]/(np.sum(values)))
explained_virances

[0.7296244541329995,
 0.22850761786701704,
 0.036689218892828605,
 0.005178709107154909]

In [19]:
np.cumsum(explained_virances)

array([0.72962445, 0.95813207, 0.99482129, 1.        ])

In [17]:
# projecting
df[df.columns]=df.dot(vectors)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0           2.640270         -5.204041          -2.488621         -0.117033
1           2.670730         -4.666910          -2.466898         -0.107536
2           2.454606         -4.773636          -2.288321         -0.104350
3           2.545517         -4.648463          -2.212378         -0.278417
4           2.561228         -5.258629          -2.392226         -0.155513

In [18]:
from sklearn.linear_model import LogisticRegression
df2 = df.iloc[:,0:2]

df4 = df.iloc[:, 0:3]

#modeMod1
lr1 = LogisticRegression()
lr1.fit(df, y)
print("all data: ", lr1.score(df, y))

#modeMod1
lr2 = LogisticRegression()
lr2.fit(df4, y)
print("3 PCs:   ", lr2.score(df4, y))

#modeMod1
lr3 = LogisticRegression()
lr3.fit(df2, y)
print("2 PCs:    ", lr3.score(df2, y))

all data:  0.9733333333333334
3 PCs:    0.9666666666666667
2 PCs:     0.9333333333333333


C:\Users\MA\AppData\Roaming\Python\Python38\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
